esphome:
  name: goodwe-tuinhuis

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "Nova"
  password: "Jolie2012"

  ap:
    ssid: "Goodwe-Tuinhuis Fallback Hotspot"
    password: "1m5CtEmNuPXv"

captive_portal:

# ================================================================
# UART - GoodWe RS485
# ================================================================
uart:
  id: uart_goodwe
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 9600
  parity: NONE
  stop_bits: 1

# ================================================================
# Modbus
# ================================================================
modbus:
  id: modbus_goodwe
  uart_id: uart_goodwe
  flow_control_pin: GPIO4

# ================================================================
# GoodWe Modbus Controller
# ================================================================
modbus_controller:
  - id: goodwe
    address: 247
    modbus_id: modbus_goodwe
    update_interval: 5s